name: 'Scheduler'

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch: {}

jobs:
  execute-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Check out repository
        uses: actions/checkout@v3  
      - name: Run something
        run:  | 
          curl ident.me 
      - name: Run workflows action..
      - uses: actions/checkout@v3
      - uses: ./.github/action/actions
        env:
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

